package com.appatstudio.epicdungeontactics2.global.managers.savedInfo;

public enum PlayerStatsTrackerFlagsEnum {
    GOLD_COLLECTED, DEEPEST_STAGE,
    SKILL_POINTS_USED, PERKS_UPGRADED,
    BOSSES_KILLED, KILLED_ENEMIES, DMG_DEALT, HIGHEST_DMG_DEALT,

    UNIQUE_ENEMIES_SLAYED, CHESTS_OPENED, ROOMS_CLEARED,
    HEROES_UNLOCKED, WEAPONS_UPGRADED
}
