package com.appatstudio.epicdungeontactics2.global.stats.itemGenerator;

import com.appatstudio.epicdungeontactics2.global.enums.SpellEnum;
import com.appatstudio.epicdungeontactics2.global.enums.itemEnums.ItemEnum;
import com.appatstudio.epicdungeontactics2.global.enums.itemEnums.ItemRarityEnum;
import com.appatstudio.epicdungeontactics2.global.enums.itemEnums.ItemTypeEnum;
import com.appatstudio.epicdungeontactics2.global.stats.items.ArmorPrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.ArrowPrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.BookPrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.BowPrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.FoodPrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.HelmetPrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.MelePrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.NecklacePrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.RingPrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.ShieldPrototype;
import com.appatstudio.epicdungeontactics2.global.stats.items.StaffPrototype;

import java.util.HashMap;

public class ItemStatsConfig {

    public static final HashMap<ItemEnum, ArmorPrototype> basicArmorStats;
    public static final HashMap<ItemEnum, ArrowPrototype> basicArrowStats;
    public static final HashMap<ItemEnum, BookPrototype> basicBookStats;
    public static final HashMap<ItemEnum, FoodPrototype> basicFoodStats;
    public static final HashMap<ItemEnum, HelmetPrototype> basicHelmetStats;
    public static final HashMap<ItemEnum, NecklacePrototype> basicNecklaceStats;
    public static final HashMap<ItemEnum, RingPrototype> basicRingStats;
    public static final HashMap<ItemEnum, ShieldPrototype> basicShieldStats;
    public static final HashMap<ItemEnum, MelePrototype> basicMeleStats;
    public static final HashMap<ItemEnum, BowPrototype> basicBowStats;
    public static final HashMap<ItemEnum, StaffPrototype> basicStaffStats;

    public static final HashMap<ItemEnum, ArmorPrototype> lvlArmorStats;
    public static final HashMap<ItemEnum, ArrowPrototype> lvlArrowStats;
    public static final HashMap<ItemEnum, BookPrototype> lvlBookStats;
    public static final HashMap<ItemEnum, FoodPrototype> lvlFoodStats;
    public static final HashMap<ItemEnum, HelmetPrototype> lvlHelmetStats;
    public static final HashMap<ItemEnum, NecklacePrototype> lvlNecklaceStats;
    public static final HashMap<ItemEnum, RingPrototype> lvlRingStats;
    public static final HashMap<ItemEnum, ShieldPrototype> lvlShieldStats;
    public static final HashMap<ItemEnum, MelePrototype> lvlMeleStats;
    public static final HashMap<ItemEnum, BowPrototype> lvlBowStats;
    public static final HashMap<ItemEnum, StaffPrototype> lvlStaffStats;

    static {

        basicArmorStats = new HashMap<>();
        basicArmorStats.put(ItemEnum.ARMORv0, new ArmorPrototype(ItemEnum.ARMORv0, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv1, new ArmorPrototype(ItemEnum.ARMORv1, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv2, new ArmorPrototype(ItemEnum.ARMORv2, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv3, new ArmorPrototype(ItemEnum.ARMORv3, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv4, new ArmorPrototype(ItemEnum.ARMORv4, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv5, new ArmorPrototype(ItemEnum.ARMORv5, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv6, new ArmorPrototype(ItemEnum.ARMORv6, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv7, new ArmorPrototype(ItemEnum.ARMORv7, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv8, new ArmorPrototype(ItemEnum.ARMORv8, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv9, new ArmorPrototype(ItemEnum.ARMORv9, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv10, new ArmorPrototype(ItemEnum.ARMORv10, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv11, new ArmorPrototype(ItemEnum.ARMORv11, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv12, new ArmorPrototype(ItemEnum.ARMORv12, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv13, new ArmorPrototype(ItemEnum.ARMORv13, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv14, new ArmorPrototype(ItemEnum.ARMORv14, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv15, new ArmorPrototype(ItemEnum.ARMORv15, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv16, new ArmorPrototype(ItemEnum.ARMORv16, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv17, new ArmorPrototype(ItemEnum.ARMORv17, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv18, new ArmorPrototype(ItemEnum.ARMORv18, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv19, new ArmorPrototype(ItemEnum.ARMORv19, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv20, new ArmorPrototype(ItemEnum.ARMORv20, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv21, new ArmorPrototype(ItemEnum.ARMORv21, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv22, new ArmorPrototype(ItemEnum.ARMORv22, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv23, new ArmorPrototype(ItemEnum.ARMORv23, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv24, new ArmorPrototype(ItemEnum.ARMORv24, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv25, new ArmorPrototype(ItemEnum.ARMORv25, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv26, new ArmorPrototype(ItemEnum.ARMORv26, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArmorStats.put(ItemEnum.ARMORv27, new ArmorPrototype(ItemEnum.ARMORv27, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));

        basicArrowStats = new HashMap<>();
        basicArrowStats.put(ItemEnum.ARROWv0, new ArrowPrototype(ItemEnum.ARROWv0, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArrowStats.put(ItemEnum.ARROWv1, new ArrowPrototype(ItemEnum.ARROWv1, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArrowStats.put(ItemEnum.ARROWv2, new ArrowPrototype(ItemEnum.ARROWv2, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArrowStats.put(ItemEnum.ARROWv3, new ArrowPrototype(ItemEnum.ARROWv3, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArrowStats.put(ItemEnum.ARROWv4, new ArrowPrototype(ItemEnum.ARROWv4, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArrowStats.put(ItemEnum.ARROWv5, new ArrowPrototype(ItemEnum.ARROWv5, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArrowStats.put(ItemEnum.ARROWv6, new ArrowPrototype(ItemEnum.ARROWv6, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArrowStats.put(ItemEnum.ARROWv7, new ArrowPrototype(ItemEnum.ARROWv7, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArrowStats.put(ItemEnum.ARROWv8, new ArrowPrototype(ItemEnum.ARROWv8, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        basicArrowStats.put(ItemEnum.ARROWv9, new ArrowPrototype(ItemEnum.ARROWv9, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));

        basicBookStats = new HashMap<>();
        basicBookStats.put(ItemEnum.BOOKv0, new BookPrototype(ItemEnum.BOOKv0, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        basicBookStats.put(ItemEnum.BOOKv1, new BookPrototype(ItemEnum.BOOKv1, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        basicBookStats.put(ItemEnum.BOOKv2, new BookPrototype(ItemEnum.BOOKv2, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        basicBookStats.put(ItemEnum.BOOKv3, new BookPrototype(ItemEnum.BOOKv3, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        basicBookStats.put(ItemEnum.BOOKv4, new BookPrototype(ItemEnum.BOOKv4, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        basicBookStats.put(ItemEnum.BOOKv5, new BookPrototype(ItemEnum.BOOKv5, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));

        basicBowStats = new HashMap<>();
        basicBowStats.put(ItemEnum.BOWv0, new BowPrototype(ItemEnum.BOWv0, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv1, new BowPrototype(ItemEnum.BOWv1, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv2, new BowPrototype(ItemEnum.BOWv2, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv3, new BowPrototype(ItemEnum.BOWv3, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv4, new BowPrototype(ItemEnum.BOWv4, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv5, new BowPrototype(ItemEnum.BOWv5, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv6, new BowPrototype(ItemEnum.BOWv6, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv7, new BowPrototype(ItemEnum.BOWv7, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv8, new BowPrototype(ItemEnum.BOWv8, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv9, new BowPrototype(ItemEnum.BOWv9, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv10, new BowPrototype(ItemEnum.BOWv10, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv11, new BowPrototype(ItemEnum.BOWv11, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv12, new BowPrototype(ItemEnum.BOWv12, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv13, new BowPrototype(ItemEnum.BOWv13, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv14, new BowPrototype(ItemEnum.BOWv14, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv15, new BowPrototype(ItemEnum.BOWv15, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv16, new BowPrototype(ItemEnum.BOWv16, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv17, new BowPrototype(ItemEnum.BOWv17, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv18, new BowPrototype(ItemEnum.BOWv18, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv19, new BowPrototype(ItemEnum.BOWv19, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv20, new BowPrototype(ItemEnum.BOWv20, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv21, new BowPrototype(ItemEnum.BOWv21, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv22, new BowPrototype(ItemEnum.BOWv22, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv23, new BowPrototype(ItemEnum.BOWv23, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv24, new BowPrototype(ItemEnum.BOWv24, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv25, new BowPrototype(ItemEnum.BOWv25, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv26, new BowPrototype(ItemEnum.BOWv26, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv27, new BowPrototype(ItemEnum.BOWv27, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv28, new BowPrototype(ItemEnum.BOWv28, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        basicBowStats.put(ItemEnum.BOWv29, new BowPrototype(ItemEnum.BOWv29, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));


        basicFoodStats = new HashMap<>();
        basicFoodStats.put(ItemEnum.FOODv0, new FoodPrototype(ItemEnum.FOODv0, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv1, new FoodPrototype(ItemEnum.FOODv1, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv2, new FoodPrototype(ItemEnum.FOODv2, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv3, new FoodPrototype(ItemEnum.FOODv3, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv4, new FoodPrototype(ItemEnum.FOODv4, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv5, new FoodPrototype(ItemEnum.FOODv5, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv6, new FoodPrototype(ItemEnum.FOODv6, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv7, new FoodPrototype(ItemEnum.FOODv7, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv8, new FoodPrototype(ItemEnum.FOODv8, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv9, new FoodPrototype(ItemEnum.FOODv9, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        basicFoodStats.put(ItemEnum.FOODv10, new FoodPrototype(ItemEnum.FOODv10, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));


        basicHelmetStats = new HashMap<>();
        basicHelmetStats.put(ItemEnum.HELMETv0, new HelmetPrototype(ItemEnum.HELMETv0, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));
        basicHelmetStats.put(ItemEnum.HELMETv1, new HelmetPrototype(ItemEnum.HELMETv1, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));
        basicHelmetStats.put(ItemEnum.HELMETv2, new HelmetPrototype(ItemEnum.HELMETv2, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));
        basicHelmetStats.put(ItemEnum.HELMETv3, new HelmetPrototype(ItemEnum.HELMETv3, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));
        basicHelmetStats.put(ItemEnum.HELMETv4, new HelmetPrototype(ItemEnum.HELMETv4, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));
        basicHelmetStats.put(ItemEnum.HELMETv5, new HelmetPrototype(ItemEnum.HELMETv5, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));
        basicHelmetStats.put(ItemEnum.HELMETv6, new HelmetPrototype(ItemEnum.HELMETv6, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));
        basicHelmetStats.put(ItemEnum.HELMETv7, new HelmetPrototype(ItemEnum.HELMETv7, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));
        basicHelmetStats.put(ItemEnum.HELMETv8, new HelmetPrototype(ItemEnum.HELMETv8, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));
        basicHelmetStats.put(ItemEnum.HELMETv9, new HelmetPrototype(ItemEnum.HELMETv9, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.GREEN));


        basicNecklaceStats = new HashMap<>();
        basicNecklaceStats.put(ItemEnum.NECKLACEv0, new NecklacePrototype(ItemEnum.NECKLACEv0, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv1, new NecklacePrototype(ItemEnum.NECKLACEv1, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv2, new NecklacePrototype(ItemEnum.NECKLACEv2, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv3, new NecklacePrototype(ItemEnum.NECKLACEv3, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv4, new NecklacePrototype(ItemEnum.NECKLACEv4, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv5, new NecklacePrototype(ItemEnum.NECKLACEv5, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv6, new NecklacePrototype(ItemEnum.NECKLACEv6, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv7, new NecklacePrototype(ItemEnum.NECKLACEv7, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv8, new NecklacePrototype(ItemEnum.NECKLACEv8, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv9, new NecklacePrototype(ItemEnum.NECKLACEv9, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv10, new NecklacePrototype(ItemEnum.NECKLACEv10, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        basicNecklaceStats.put(ItemEnum.NECKLACEv11, new NecklacePrototype(ItemEnum.NECKLACEv11, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));


        basicRingStats = new HashMap<>();
        basicRingStats.put(ItemEnum.RINGv0, new RingPrototype(ItemEnum.RINGv0, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv1, new RingPrototype(ItemEnum.RINGv1, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv2, new RingPrototype(ItemEnum.RINGv2, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv3, new RingPrototype(ItemEnum.RINGv3, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv4, new RingPrototype(ItemEnum.RINGv4, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv5, new RingPrototype(ItemEnum.RINGv5, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv6, new RingPrototype(ItemEnum.RINGv6, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv7, new RingPrototype(ItemEnum.RINGv7, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv8, new RingPrototype(ItemEnum.RINGv8, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv9, new RingPrototype(ItemEnum.RINGv9, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv10, new RingPrototype(ItemEnum.RINGv10, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv11, new RingPrototype(ItemEnum.RINGv11, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv12, new RingPrototype(ItemEnum.RINGv12, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv13, new RingPrototype(ItemEnum.RINGv13, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv14, new RingPrototype(ItemEnum.RINGv14, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv15, new RingPrototype(ItemEnum.RINGv15, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv16, new RingPrototype(ItemEnum.RINGv16, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv17, new RingPrototype(ItemEnum.RINGv17, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv18, new RingPrototype(ItemEnum.RINGv18, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv19, new RingPrototype(ItemEnum.RINGv19, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv20, new RingPrototype(ItemEnum.RINGv20, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        basicRingStats.put(ItemEnum.RINGv21, new RingPrototype(ItemEnum.RINGv21, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));


        basicStaffStats = new HashMap<>();
        basicStaffStats.put(ItemEnum.STAFFv0, new StaffPrototype(ItemEnum.STAFFv0, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        basicStaffStats.put(ItemEnum.STAFFv1, new StaffPrototype(ItemEnum.STAFFv1, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        basicStaffStats.put(ItemEnum.STAFFv2, new StaffPrototype(ItemEnum.STAFFv2, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        basicStaffStats.put(ItemEnum.STAFFv3, new StaffPrototype(ItemEnum.STAFFv3, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        basicStaffStats.put(ItemEnum.STAFFv4, new StaffPrototype(ItemEnum.STAFFv4, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        basicStaffStats.put(ItemEnum.STAFFv5, new StaffPrototype(ItemEnum.STAFFv5, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        basicStaffStats.put(ItemEnum.STAFFv6, new StaffPrototype(ItemEnum.STAFFv6, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        basicStaffStats.put(ItemEnum.STAFFv7, new StaffPrototype(ItemEnum.STAFFv7, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));


        basicShieldStats = new HashMap<>();
        basicShieldStats.put(ItemEnum.SHIELDv0, new ShieldPrototype(ItemEnum.SHIELDv0, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv1, new ShieldPrototype(ItemEnum.SHIELDv1, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv2, new ShieldPrototype(ItemEnum.SHIELDv2, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv3, new ShieldPrototype(ItemEnum.SHIELDv3, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv4, new ShieldPrototype(ItemEnum.SHIELDv4, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv5, new ShieldPrototype(ItemEnum.SHIELDv5, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv6, new ShieldPrototype(ItemEnum.SHIELDv6, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv7, new ShieldPrototype(ItemEnum.SHIELDv7, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv8, new ShieldPrototype(ItemEnum.SHIELDv8, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv9, new ShieldPrototype(ItemEnum.SHIELDv9, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv10, new ShieldPrototype(ItemEnum.SHIELDv10, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv11, new ShieldPrototype(ItemEnum.SHIELDv11, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv12, new ShieldPrototype(ItemEnum.SHIELDv12, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv13, new ShieldPrototype(ItemEnum.SHIELDv13, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        basicShieldStats.put(ItemEnum.SHIELDv14, new ShieldPrototype(ItemEnum.SHIELDv14, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));


        basicMeleStats = new HashMap<>();
        basicMeleStats.put(ItemEnum.SWORDv0,  new MelePrototype(ItemEnum.SWORDv0, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv1, new MelePrototype(ItemEnum.SWORDv1, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv2, new MelePrototype(ItemEnum.SWORDv2, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv3, new MelePrototype(ItemEnum.SWORDv3, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv4, new MelePrototype(ItemEnum.SWORDv4, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv5, new MelePrototype(ItemEnum.SWORDv5, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv6, new MelePrototype(ItemEnum.SWORDv6, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv7, new MelePrototype(ItemEnum.SWORDv7, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv8, new MelePrototype(ItemEnum.SWORDv8, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv9, new MelePrototype(ItemEnum.SWORDv9, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv10, new MelePrototype(ItemEnum.SWORDv10, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv11, new MelePrototype(ItemEnum.SWORDv11, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv12, new MelePrototype(ItemEnum.SWORDv12, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv13, new MelePrototype(ItemEnum.SWORDv13, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv14, new MelePrototype(ItemEnum.SWORDv14, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv15, new MelePrototype(ItemEnum.SWORDv15, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv16, new MelePrototype(ItemEnum.SWORDv16, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv17, new MelePrototype(ItemEnum.SWORDv17, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv18, new MelePrototype(ItemEnum.SWORDv18, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv19, new MelePrototype(ItemEnum.SWORDv19, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv20, new MelePrototype(ItemEnum.SWORDv20, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv21, new MelePrototype(ItemEnum.SWORDv21, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv22, new MelePrototype(ItemEnum.SWORDv22, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv23, new MelePrototype(ItemEnum.SWORDv23, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv24, new MelePrototype(ItemEnum.SWORDv24, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv25, new MelePrototype(ItemEnum.SWORDv25, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv26, new MelePrototype(ItemEnum.SWORDv26, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv27, new MelePrototype(ItemEnum.SWORDv27, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv28, new MelePrototype(ItemEnum.SWORDv28, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv29, new MelePrototype(ItemEnum.SWORDv29, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv30, new MelePrototype(ItemEnum.SWORDv30, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv31, new MelePrototype(ItemEnum.SWORDv31, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv32, new MelePrototype(ItemEnum.SWORDv32, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv33, new MelePrototype(ItemEnum.SWORDv33, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv34, new MelePrototype(ItemEnum.SWORDv34, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv35, new MelePrototype(ItemEnum.SWORDv35, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv36, new MelePrototype(ItemEnum.SWORDv36, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv37, new MelePrototype(ItemEnum.SWORDv37, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv38, new MelePrototype(ItemEnum.SWORDv38, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv39, new MelePrototype(ItemEnum.SWORDv39, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv40, new MelePrototype(ItemEnum.SWORDv40, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv41, new MelePrototype(ItemEnum.SWORDv41, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv42, new MelePrototype(ItemEnum.SWORDv42, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv43, new MelePrototype(ItemEnum.SWORDv43, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv44, new MelePrototype(ItemEnum.SWORDv44, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv45, new MelePrototype(ItemEnum.SWORDv45, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv46, new MelePrototype(ItemEnum.SWORDv46, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv47, new MelePrototype(ItemEnum.SWORDv47, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv48, new MelePrototype(ItemEnum.SWORDv48, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv49, new MelePrototype(ItemEnum.SWORDv49, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv50, new MelePrototype(ItemEnum.SWORDv50, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv51, new MelePrototype(ItemEnum.SWORDv51, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv52, new MelePrototype(ItemEnum.SWORDv52, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv53, new MelePrototype(ItemEnum.SWORDv53, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv54, new MelePrototype(ItemEnum.SWORDv54, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv55, new MelePrototype(ItemEnum.SWORDv55, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv56, new MelePrototype(ItemEnum.SWORDv56, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv57, new MelePrototype(ItemEnum.SWORDv57, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv58, new MelePrototype(ItemEnum.SWORDv58, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv59, new MelePrototype(ItemEnum.SWORDv59, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv60, new MelePrototype(ItemEnum.SWORDv60, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv61, new MelePrototype(ItemEnum.SWORDv61, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv62, new MelePrototype(ItemEnum.SWORDv62, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv63, new MelePrototype(ItemEnum.SWORDv63, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv64, new MelePrototype(ItemEnum.SWORDv64, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv65, new MelePrototype(ItemEnum.SWORDv65, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv66, new MelePrototype(ItemEnum.SWORDv66, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv67, new MelePrototype(ItemEnum.SWORDv67, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv68, new MelePrototype(ItemEnum.SWORDv68, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv69, new MelePrototype(ItemEnum.SWORDv69, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv70, new MelePrototype(ItemEnum.SWORDv70, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv71, new MelePrototype(ItemEnum.SWORDv71, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        basicMeleStats.put(ItemEnum.SWORDv72, new MelePrototype(ItemEnum.SWORDv72, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));


        //-------------------------------------------------------------------------------------------------------------------------------


        lvlArmorStats = new HashMap<>();
        lvlArmorStats.put(ItemEnum.ARMORv0, new ArmorPrototype(ItemEnum.ARMORv0, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv1, new ArmorPrototype(ItemEnum.ARMORv1, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv2, new ArmorPrototype(ItemEnum.ARMORv2, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv3, new ArmorPrototype(ItemEnum.ARMORv3, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv4, new ArmorPrototype(ItemEnum.ARMORv4, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv5, new ArmorPrototype(ItemEnum.ARMORv5, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv6, new ArmorPrototype(ItemEnum.ARMORv6, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv7, new ArmorPrototype(ItemEnum.ARMORv7, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv8, new ArmorPrototype(ItemEnum.ARMORv8, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv9, new ArmorPrototype(ItemEnum.ARMORv9, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv10, new ArmorPrototype(ItemEnum.ARMORv10, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv11, new ArmorPrototype(ItemEnum.ARMORv11, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv12, new ArmorPrototype(ItemEnum.ARMORv12, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv13, new ArmorPrototype(ItemEnum.ARMORv13, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv14, new ArmorPrototype(ItemEnum.ARMORv14, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv15, new ArmorPrototype(ItemEnum.ARMORv15, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv16, new ArmorPrototype(ItemEnum.ARMORv16, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv17, new ArmorPrototype(ItemEnum.ARMORv17, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv18, new ArmorPrototype(ItemEnum.ARMORv18, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv19, new ArmorPrototype(ItemEnum.ARMORv19, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv20, new ArmorPrototype(ItemEnum.ARMORv20, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv21, new ArmorPrototype(ItemEnum.ARMORv21, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv22, new ArmorPrototype(ItemEnum.ARMORv22, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv23, new ArmorPrototype(ItemEnum.ARMORv23, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv24, new ArmorPrototype(ItemEnum.ARMORv24, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv25, new ArmorPrototype(ItemEnum.ARMORv25, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv26, new ArmorPrototype(ItemEnum.ARMORv26, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArmorStats.put(ItemEnum.ARMORv27, new ArmorPrototype(ItemEnum.ARMORv27, ItemTypeEnum.ARMOR, 10, 10, 1, ItemRarityEnum.WHITE));

        lvlArrowStats = new HashMap<>();
        lvlArrowStats.put(ItemEnum.ARROWv0, new ArrowPrototype(ItemEnum.ARROWv0, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArrowStats.put(ItemEnum.ARROWv1, new ArrowPrototype(ItemEnum.ARROWv1, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArrowStats.put(ItemEnum.ARROWv2, new ArrowPrototype(ItemEnum.ARROWv2, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArrowStats.put(ItemEnum.ARROWv3, new ArrowPrototype(ItemEnum.ARROWv3, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArrowStats.put(ItemEnum.ARROWv4, new ArrowPrototype(ItemEnum.ARROWv4, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArrowStats.put(ItemEnum.ARROWv5, new ArrowPrototype(ItemEnum.ARROWv5, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArrowStats.put(ItemEnum.ARROWv6, new ArrowPrototype(ItemEnum.ARROWv6, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArrowStats.put(ItemEnum.ARROWv7, new ArrowPrototype(ItemEnum.ARROWv7, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArrowStats.put(ItemEnum.ARROWv8, new ArrowPrototype(ItemEnum.ARROWv8, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));
        lvlArrowStats.put(ItemEnum.ARROWv9, new ArrowPrototype(ItemEnum.ARROWv9, ItemTypeEnum.ARROW, 10, 10, 1, ItemRarityEnum.WHITE));

        lvlBookStats = new HashMap<>();
        lvlBookStats.put(ItemEnum.BOOKv0, new BookPrototype(ItemEnum.BOOKv0, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        lvlBookStats.put(ItemEnum.BOOKv1, new BookPrototype(ItemEnum.BOOKv1, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        lvlBookStats.put(ItemEnum.BOOKv2, new BookPrototype(ItemEnum.BOOKv2, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        lvlBookStats.put(ItemEnum.BOOKv3, new BookPrototype(ItemEnum.BOOKv3, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        lvlBookStats.put(ItemEnum.BOOKv4, new BookPrototype(ItemEnum.BOOKv4, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));
        lvlBookStats.put(ItemEnum.BOOKv5, new BookPrototype(ItemEnum.BOOKv5, ItemTypeEnum.BOOK, 10, 10, ItemRarityEnum.WHITE));

        lvlBowStats = new HashMap<>();
        lvlBowStats.put(ItemEnum.BOWv0, new BowPrototype(ItemEnum.BOWv0, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv1, new BowPrototype(ItemEnum.BOWv1, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv2, new BowPrototype(ItemEnum.BOWv2, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv3, new BowPrototype(ItemEnum.BOWv3, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv4, new BowPrototype(ItemEnum.BOWv4, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv5, new BowPrototype(ItemEnum.BOWv5, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv6, new BowPrototype(ItemEnum.BOWv6, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv7, new BowPrototype(ItemEnum.BOWv7, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv8, new BowPrototype(ItemEnum.BOWv8, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv9, new BowPrototype(ItemEnum.BOWv9, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv10, new BowPrototype(ItemEnum.BOWv10, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv11, new BowPrototype(ItemEnum.BOWv11, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv12, new BowPrototype(ItemEnum.BOWv12, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv13, new BowPrototype(ItemEnum.BOWv13, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv14, new BowPrototype(ItemEnum.BOWv14, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv15, new BowPrototype(ItemEnum.BOWv15, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv16, new BowPrototype(ItemEnum.BOWv16, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv17, new BowPrototype(ItemEnum.BOWv17, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv18, new BowPrototype(ItemEnum.BOWv18, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv19, new BowPrototype(ItemEnum.BOWv19, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv20, new BowPrototype(ItemEnum.BOWv20, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv21, new BowPrototype(ItemEnum.BOWv21, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv22, new BowPrototype(ItemEnum.BOWv22, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv23, new BowPrototype(ItemEnum.BOWv23, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv24, new BowPrototype(ItemEnum.BOWv24, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv25, new BowPrototype(ItemEnum.BOWv25, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv26, new BowPrototype(ItemEnum.BOWv26, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv27, new BowPrototype(ItemEnum.BOWv27, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv28, new BowPrototype(ItemEnum.BOWv28, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlBowStats.put(ItemEnum.BOWv29, new BowPrototype(ItemEnum.BOWv29, ItemTypeEnum.BOW, 10, 10, 10, ItemRarityEnum.WHITE));


        lvlFoodStats = new HashMap<>();
        lvlFoodStats.put(ItemEnum.FOODv0, new FoodPrototype(ItemEnum.FOODv0, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv1, new FoodPrototype(ItemEnum.FOODv1, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv2, new FoodPrototype(ItemEnum.FOODv2, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv3, new FoodPrototype(ItemEnum.FOODv3, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv4, new FoodPrototype(ItemEnum.FOODv4, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv5, new FoodPrototype(ItemEnum.FOODv5, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv6, new FoodPrototype(ItemEnum.FOODv6, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv7, new FoodPrototype(ItemEnum.FOODv7, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv8, new FoodPrototype(ItemEnum.FOODv8, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv9, new FoodPrototype(ItemEnum.FOODv9, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));
        lvlFoodStats.put(ItemEnum.FOODv10, new FoodPrototype(ItemEnum.FOODv10, ItemTypeEnum.FOOD, 10, 10, 5, ItemRarityEnum.WHITE));


        lvlHelmetStats = new HashMap<>();
        lvlHelmetStats.put(ItemEnum.HELMETv0, new HelmetPrototype(ItemEnum.HELMETv0, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));
        lvlHelmetStats.put(ItemEnum.HELMETv1, new HelmetPrototype(ItemEnum.HELMETv1, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));
        lvlHelmetStats.put(ItemEnum.HELMETv2, new HelmetPrototype(ItemEnum.HELMETv2, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));
        lvlHelmetStats.put(ItemEnum.HELMETv3, new HelmetPrototype(ItemEnum.HELMETv3, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));
        lvlHelmetStats.put(ItemEnum.HELMETv4, new HelmetPrototype(ItemEnum.HELMETv4, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));
        lvlHelmetStats.put(ItemEnum.HELMETv5, new HelmetPrototype(ItemEnum.HELMETv5, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));
        lvlHelmetStats.put(ItemEnum.HELMETv6, new HelmetPrototype(ItemEnum.HELMETv6, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));
        lvlHelmetStats.put(ItemEnum.HELMETv7, new HelmetPrototype(ItemEnum.HELMETv7, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));
        lvlHelmetStats.put(ItemEnum.HELMETv8, new HelmetPrototype(ItemEnum.HELMETv8, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));
        lvlHelmetStats.put(ItemEnum.HELMETv9, new HelmetPrototype(ItemEnum.HELMETv9, ItemTypeEnum.HELMET, 10, 10, ItemRarityEnum.WHITE));


        lvlNecklaceStats = new HashMap<>();
        lvlNecklaceStats.put(ItemEnum.NECKLACEv0, new NecklacePrototype(ItemEnum.NECKLACEv0, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv1, new NecklacePrototype(ItemEnum.NECKLACEv1, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv2, new NecklacePrototype(ItemEnum.NECKLACEv2, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv3, new NecklacePrototype(ItemEnum.NECKLACEv3, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv4, new NecklacePrototype(ItemEnum.NECKLACEv4, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv5, new NecklacePrototype(ItemEnum.NECKLACEv5, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv6, new NecklacePrototype(ItemEnum.NECKLACEv6, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv7, new NecklacePrototype(ItemEnum.NECKLACEv7, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv8, new NecklacePrototype(ItemEnum.NECKLACEv8, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv9, new NecklacePrototype(ItemEnum.NECKLACEv9, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv10, new NecklacePrototype(ItemEnum.NECKLACEv10, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));
        lvlNecklaceStats.put(ItemEnum.NECKLACEv11, new NecklacePrototype(ItemEnum.NECKLACEv11, ItemTypeEnum.NECKLACE, 10, 10, ItemRarityEnum.WHITE));


        lvlRingStats = new HashMap<>();
        lvlRingStats.put(ItemEnum.RINGv0, new RingPrototype(ItemEnum.RINGv0, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv1, new RingPrototype(ItemEnum.RINGv1, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv2, new RingPrototype(ItemEnum.RINGv2, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv3, new RingPrototype(ItemEnum.RINGv3, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv4, new RingPrototype(ItemEnum.RINGv4, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv5, new RingPrototype(ItemEnum.RINGv5, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv6, new RingPrototype(ItemEnum.RINGv6, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv7, new RingPrototype(ItemEnum.RINGv7, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv8, new RingPrototype(ItemEnum.RINGv8, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv9, new RingPrototype(ItemEnum.RINGv9, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv10, new RingPrototype(ItemEnum.RINGv10, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv11, new RingPrototype(ItemEnum.RINGv11, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv12, new RingPrototype(ItemEnum.RINGv12, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv13, new RingPrototype(ItemEnum.RINGv13, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv14, new RingPrototype(ItemEnum.RINGv14, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv15, new RingPrototype(ItemEnum.RINGv15, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv16, new RingPrototype(ItemEnum.RINGv16, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv17, new RingPrototype(ItemEnum.RINGv17, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv18, new RingPrototype(ItemEnum.RINGv18, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv19, new RingPrototype(ItemEnum.RINGv19, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv20, new RingPrototype(ItemEnum.RINGv20, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));
        lvlRingStats.put(ItemEnum.RINGv21, new RingPrototype(ItemEnum.RINGv21, ItemTypeEnum.RING, 10, 10, ItemRarityEnum.WHITE));


        lvlStaffStats = new HashMap<>();
        lvlStaffStats.put(ItemEnum.STAFFv0, new StaffPrototype(ItemEnum.STAFFv0, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        lvlStaffStats.put(ItemEnum.STAFFv1, new StaffPrototype(ItemEnum.STAFFv1, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        lvlStaffStats.put(ItemEnum.STAFFv2, new StaffPrototype(ItemEnum.STAFFv2, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        lvlStaffStats.put(ItemEnum.STAFFv3, new StaffPrototype(ItemEnum.STAFFv3, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        lvlStaffStats.put(ItemEnum.STAFFv4, new StaffPrototype(ItemEnum.STAFFv4, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        lvlStaffStats.put(ItemEnum.STAFFv5, new StaffPrototype(ItemEnum.STAFFv5, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        lvlStaffStats.put(ItemEnum.STAFFv6, new StaffPrototype(ItemEnum.STAFFv6, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));
        lvlStaffStats.put(ItemEnum.STAFFv7, new StaffPrototype(ItemEnum.STAFFv7, ItemTypeEnum.STAFF, 10, 10, SpellEnum.BURNING, 10, 0.5f, ItemRarityEnum.WHITE));


        lvlShieldStats = new HashMap<>();
        lvlShieldStats.put(ItemEnum.SHIELDv0, new ShieldPrototype(ItemEnum.SHIELDv0, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv1, new ShieldPrototype(ItemEnum.SHIELDv1, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv2, new ShieldPrototype(ItemEnum.SHIELDv2, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv3, new ShieldPrototype(ItemEnum.SHIELDv3, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv4, new ShieldPrototype(ItemEnum.SHIELDv4, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv5, new ShieldPrototype(ItemEnum.SHIELDv5, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv6, new ShieldPrototype(ItemEnum.SHIELDv6, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv7, new ShieldPrototype(ItemEnum.SHIELDv7, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv8, new ShieldPrototype(ItemEnum.SHIELDv8, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv9, new ShieldPrototype(ItemEnum.SHIELDv9, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv10, new ShieldPrototype(ItemEnum.SHIELDv10, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv11, new ShieldPrototype(ItemEnum.SHIELDv11, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv12, new ShieldPrototype(ItemEnum.SHIELDv12, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv13, new ShieldPrototype(ItemEnum.SHIELDv13, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlShieldStats.put(ItemEnum.SHIELDv14, new ShieldPrototype(ItemEnum.SHIELDv14, ItemTypeEnum.SHIELD, 10, 10, 10, ItemRarityEnum.WHITE));


        lvlMeleStats = new HashMap<>();
        lvlMeleStats.put(ItemEnum.SWORDv0,  new MelePrototype(ItemEnum.SWORDv0, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv1, new MelePrototype(ItemEnum.SWORDv1, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv2, new MelePrototype(ItemEnum.SWORDv2, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv3, new MelePrototype(ItemEnum.SWORDv3, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv4, new MelePrototype(ItemEnum.SWORDv4, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv5, new MelePrototype(ItemEnum.SWORDv5, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv6, new MelePrototype(ItemEnum.SWORDv6, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv7, new MelePrototype(ItemEnum.SWORDv7, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv8, new MelePrototype(ItemEnum.SWORDv8, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv9, new MelePrototype(ItemEnum.SWORDv9, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv10, new MelePrototype(ItemEnum.SWORDv10, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv11, new MelePrototype(ItemEnum.SWORDv11, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv12, new MelePrototype(ItemEnum.SWORDv12, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv13, new MelePrototype(ItemEnum.SWORDv13, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv14, new MelePrototype(ItemEnum.SWORDv14, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv15, new MelePrototype(ItemEnum.SWORDv15, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv16, new MelePrototype(ItemEnum.SWORDv16, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv17, new MelePrototype(ItemEnum.SWORDv17, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv18, new MelePrototype(ItemEnum.SWORDv18, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv19, new MelePrototype(ItemEnum.SWORDv19, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv20, new MelePrototype(ItemEnum.SWORDv20, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv21, new MelePrototype(ItemEnum.SWORDv21, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv22, new MelePrototype(ItemEnum.SWORDv22, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv23, new MelePrototype(ItemEnum.SWORDv23, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv24, new MelePrototype(ItemEnum.SWORDv24, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv25, new MelePrototype(ItemEnum.SWORDv25, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv26, new MelePrototype(ItemEnum.SWORDv26, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv27, new MelePrototype(ItemEnum.SWORDv27, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv28, new MelePrototype(ItemEnum.SWORDv28, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv29, new MelePrototype(ItemEnum.SWORDv29, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv30, new MelePrototype(ItemEnum.SWORDv30, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv31, new MelePrototype(ItemEnum.SWORDv31, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv32, new MelePrototype(ItemEnum.SWORDv32, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv33, new MelePrototype(ItemEnum.SWORDv33, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv34, new MelePrototype(ItemEnum.SWORDv34, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv35, new MelePrototype(ItemEnum.SWORDv35, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv36, new MelePrototype(ItemEnum.SWORDv36, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv37, new MelePrototype(ItemEnum.SWORDv37, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv38, new MelePrototype(ItemEnum.SWORDv38, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv39, new MelePrototype(ItemEnum.SWORDv39, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv40, new MelePrototype(ItemEnum.SWORDv40, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv41, new MelePrototype(ItemEnum.SWORDv41, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv42, new MelePrototype(ItemEnum.SWORDv42, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv43, new MelePrototype(ItemEnum.SWORDv43, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv44, new MelePrototype(ItemEnum.SWORDv44, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv45, new MelePrototype(ItemEnum.SWORDv45, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv46, new MelePrototype(ItemEnum.SWORDv46, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv47, new MelePrototype(ItemEnum.SWORDv47, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv48, new MelePrototype(ItemEnum.SWORDv48, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv49, new MelePrototype(ItemEnum.SWORDv49, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv50, new MelePrototype(ItemEnum.SWORDv50, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv51, new MelePrototype(ItemEnum.SWORDv51, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv52, new MelePrototype(ItemEnum.SWORDv52, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv53, new MelePrototype(ItemEnum.SWORDv53, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv54, new MelePrototype(ItemEnum.SWORDv54, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv55, new MelePrototype(ItemEnum.SWORDv55, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv56, new MelePrototype(ItemEnum.SWORDv56, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv57, new MelePrototype(ItemEnum.SWORDv57, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv58, new MelePrototype(ItemEnum.SWORDv58, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv59, new MelePrototype(ItemEnum.SWORDv59, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv60, new MelePrototype(ItemEnum.SWORDv60, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv61, new MelePrototype(ItemEnum.SWORDv61, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv62, new MelePrototype(ItemEnum.SWORDv62, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv63, new MelePrototype(ItemEnum.SWORDv63, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv64, new MelePrototype(ItemEnum.SWORDv64, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv65, new MelePrototype(ItemEnum.SWORDv65, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv66, new MelePrototype(ItemEnum.SWORDv66, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv67, new MelePrototype(ItemEnum.SWORDv67, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv68, new MelePrototype(ItemEnum.SWORDv68, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv69, new MelePrototype(ItemEnum.SWORDv69, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv70, new MelePrototype(ItemEnum.SWORDv70, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv71, new MelePrototype(ItemEnum.SWORDv71, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));
        lvlMeleStats.put(ItemEnum.SWORDv72, new MelePrototype(ItemEnum.SWORDv72, ItemTypeEnum.MELE, 10, 10, 10, ItemRarityEnum.WHITE));


    }


}
