package com.appatstudio.epicdungeontactics2.global.enums.itemEnums;

public enum ItemEffectEnum {

    DMG_BONUS,
    STR_BONUS,
    DEX_BONUS,
    LCK_BONUS,
    INT_BONUS,
    VIT_BONUS,

    PERCENT_HP_REGEN_CLEAN_ROOM,
    PERCENT_GOLD_COLLECTED_BONUS,
    PERCENT_EXP_COLLECTED_BONUS,
    PERCENT_CHANCE_FOR_DOUBLE_ATTACK,

    PERCENT_CHANCE_FOR_DOUBLE_MOVE,
    PERCENT_HP_REGEN_KILL,
    PERCENT_ANY_DROP_CHANCE,
    PERCENT_SPELL_CHANCE,
    PERCENT_CRIT_CHANCE,

    PERCENT_CHANCE_FOR_POISONING,
    PERCENT_CHANCE_FOR_BURNING

}
