package com.appatstudio.epicdungeontactics2.global.managers.map.mapInfo;
import static com.appatstudio.epicdungeontactics2.global.enums.CharacterEnum.*;

import com.appatstudio.epicdungeontactics2.global.enums.CharacterEnum;
import com.appatstudio.epicdungeontactics2.global.enums.RoomEnum;

import java.util.HashMap;

public class MapInfoEnemyStage2 {

    private static final HashMap<RoomEnum, CharacterEnum[][]> charactersInfoMap;

    static {
        charactersInfoMap = new HashMap<>();
//python-insert-char
charactersInfoMap.put(RoomEnum.STAGE_2_FIRST_1, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, NPC_BLACKSMITH, null, null, null },
{  null, null, NPC_CITIZEN_MALE, null, null, null, null, null, NPC_BUTCHER, null, null },
{  null, null, null, null, null, HERO_BABY, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, NPC_MAGIC_SHOP, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_ALCHEMIST, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, NPC_PRINCESS, null, null, null, null },
{  null, null, null, null, null, null, null, NPC_MOUNTAIN_KING, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_FIRST_2, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, NPC_CITIZEN_MALE, null, null, null, null, null, null },
{  null, null, null, NPC_ALCHEMIST, null, null, NPC_PRINCESS, null, null, null, null },
{  null, null, null, null, null, null, null, NPC_MOUNTAIN_KING, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, HERO_BABY, null, null, null, NPC_BUTCHER, null, null },
{  null, null, null, null, null, null, NPC_BLACKSMITH, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_MAGIC_SHOP, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_FIRST_3, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_PRINCESS, NPC_CITIZEN_MALE, null, null, null, null, null, null },
{  null, NPC_MOUNTAIN_KING, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, HERO_BABY, null, null, null, null, null },
{  null, null, null, NPC_BUTCHER, null, null, null, null, NPC_BLACKSMITH, null, null },
{  null, null, null, null, NPC_ALCHEMIST, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, NPC_MAGIC_SHOP, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_FIRST_4, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_PRINCESS, null, null, null, null, null, null, null },
{  null, null, NPC_MOUNTAIN_KING, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, NPC_CITIZEN_MALE, null, null },
{  null, null, null, null, null, HERO_BABY, null, null, null, null, null },
{  null, null, NPC_ALCHEMIST, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_BUTCHER, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, NPC_BLACKSMITH, null, null, null, NPC_MAGIC_SHOP, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_1, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_BRUTE, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, MASKED_ORC, null, null, null },
{  null, null, null, null, GNOLL_SHAMAN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SHAMAN, null, null, null, null },
{  null, GNOLL_BRUTE, null, MASKED_ORC, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SHAMAN, null, GNOLL_BRUTE, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MASKED_ORC, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_BRUTE, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_2, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MASKED_ORC, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, ORC_SHAMAN, null, null, null, null, null, MASKED_ORC, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, MASKED_ORC, null, null, ORC_SHAMAN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, ORC_SHAMAN, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, MASKED_ORC, null, null, null },
{  null, null, null, ORC_SHAMAN, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_3, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, MASKED_ORC, null, null, null, null, null, null, null, null, null },
{  null, null, null, ORC_SHAMAN, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, ORC_SHAMAN, null, null, null, null, null, null, null, null },
{  null, null, null, null, GOBLIN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, MASKED_ORC, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, ORC_SHAMAN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, MASKED_ORC, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, ORC_SHAMAN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_4, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MUDDY, null, null, null, null, null, null },
{  null, null, null, null, null, null, GOBLIN, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MUDDY, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GOBLIN, null, null, null, null, GOBLIN, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, MUDDY, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GOBLIN, null, null, null, null, null, null, null },
{  null, null, null, null, null, MUDDY, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_5, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_OVERSEER, null, null, null, null, null, null, null, null },
{  null, null, null, MUDDY, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, MUDDY, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_OVERSEER, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, MUDDY, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, MUDDY, null, null, null, null, null, MUDDY, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_OVERSEER, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MUDDY, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, ORC_WARRIOR, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_6, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GOBLIN, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, GNOLL_SHAMAN, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, SWAMPY, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, SWAMPY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, SWAMPY, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, SWAMPY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_7, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_SHAMAN, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, SWAMPY, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_SHAMAN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GNOLL_SCOUT, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_SHAMAN, null, null, null },
{  null, null, null, null, null, SWAMPY, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_SCOUT, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_SHAMAN, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_8, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, SWAMPY, null, GNOLL_SCOUT, null, null },
{  null, null, null, GNOLL_SCOUT, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, SWAMPY, null, null },
{  null, SWAMPY, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_SCOUT, null, null, null, null, null, null },
{  null, null, null, null, null, null, SWAMPY, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_9, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GNOLL_SCOUT, null, null, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_SCOUT, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_SCOUT, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_OVERSEER, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_SCOUT, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_OVERSEER, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_10, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_BRUTE, null, null, null, null, null, null },
{  null, null, null, null, null, null, MUDDY, null, null, null, null },
{  null, null, MUDDY, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_BRUTE, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_BRUTE, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, null, null, null, null, MUDDY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_11, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, ORC_WARRIOR, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, MUDDY, null, null, null, null, null, ORC_WARRIOR, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, ORC_WARRIOR, null, null, null, null, MUDDY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, ORC_WARRIOR, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MUDDY, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_12, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, ORC_WARRIOR, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_SCOUT, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, ORC_WARRIOR, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, ORC_WARRIOR, null, null, GNOLL_SCOUT, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, ORC_WARRIOR, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, ORC_WARRIOR, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_13, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_SCOUT, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GOBLIN, null, null, null, null, null, null, SWAMPY, null, null },
{  null, null, null, GNOLL_SCOUT, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_SCOUT, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, SWAMPY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_SCOUT, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_14, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, ORC_SHAMAN, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, SWAMPY, null, null, null, null, null, null, null, ORC_SHAMAN, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, ORC_SHAMAN, null, null, null, null, SWAMPY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, ORC_SHAMAN, null, ORC_WARRIOR, null, null },
{  null, null, SWAMPY, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MASKED_ORC, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, ORC_SHAMAN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_15, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, ORC_WARRIOR, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_SCOUT, null, null, null, null, null, null },
{  null, null, ORC_WARRIOR, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, ORC_WARRIOR, null, null },
{  null, null, null, null, null, ORC_WARRIOR, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_SCOUT, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_SCOUT, null, ORC_WARRIOR, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, ORC_WARRIOR, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_16, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, MUDDY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_SCOUT, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_BRUTE, null, null, null, GNOLL_SCOUT, null },
{  null, null, null, GNOLL_SCOUT, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MUDDY, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_BRUTE, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, GNOLL_BRUTE, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MUDDY, null, null, null, null },
{  null, null, null, GNOLL_SCOUT, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_17, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, MUDDY, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_BRUTE, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_BRUTE, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, MUDDY, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MASKED_ORC, null, null, null, null },
{  null, null, null, GNOLL_BRUTE, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_BRUTE, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MUDDY, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_18, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MASKED_ORC, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, SWAMPY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, SWAMPY, null, null, null, null, null, MASKED_ORC, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MASKED_ORC, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, SWAMPY, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, MASKED_ORC, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, SWAMPY, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_19, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, null, null, null, null, SWAMPY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_BRUTE, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, SWAMPY, null, null, null, null, null },
{  null, null, GNOLL_BRUTE, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, SWAMPY, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, SWAMPY, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_REGULAR_20, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_BRUTE, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GOBLIN, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GOBLIN, null, null, null, null },
{  null, null, GNOLL_BRUTE, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MASKED_ORC, null, GNOLL_BRUTE, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GOBLIN, null, GNOLL_BRUTE, null, null, GOBLIN, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_BRUTE, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_BOSS_1, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_BRUTE, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_BRUTE, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_OVERSEER, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, BOSS_OGRE, null, null, GNOLL_OVERSEER, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_OVERSEER, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_BOSS_2, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, ORC_SHAMAN, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, ORC_SHAMAN, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, ORC_SHAMAN, null, null },
{  null, null, null, null, null, null, null, GNOLL_SCOUT, null, null, null },
{  null, GNOLL_SCOUT, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, BOSS_OGRE, null, null, null, null, null, null },
{  null, null, ORC_SHAMAN, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_SCOUT, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_BOSS_3, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_SHAMAN, null, null, null },
{  null, null, null, null, null, null, MUDDY, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, MUDDY, null },
{  null, null, null, null, null, null, BOSS_OGRE, null, null, null, null },
{  null, null, GNOLL_SCOUT, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_SHAMAN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MUDDY, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_2_BOSS_4, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_SHAMAN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, MASKED_ORC, null, BOSS_OGRE, null, null, null, GNOLL_SHAMAN, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, MASKED_ORC, null, null, null },
{  null, null, null, null, null, GOBLIN, null, null, null, null, null },
{  null, null, null, null, GNOLL_SHAMAN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
//python-insert-char-end

    }

    public static HashMap<RoomEnum, CharacterEnum[][]> getCharactersInfo() {
        return charactersInfoMap;
    }
}
