package com.appatstudio.epicdungeontactics2.global.managers.map.mapInfo;
import static com.appatstudio.epicdungeontactics2.global.enums.CharacterEnum.*;

import com.appatstudio.epicdungeontactics2.global.enums.CharacterEnum;
import com.appatstudio.epicdungeontactics2.global.enums.RoomEnum;

import java.util.HashMap;

public class MapInfoEnemyStage3 {

    private static final HashMap<RoomEnum, CharacterEnum[][]> charactersInfoMap;

    static {
        charactersInfoMap = new HashMap<>();
//python-insert-char
charactersInfoMap.put(RoomEnum.STAGE_3_FIRST_1, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, NPC_ALCHEMIST, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_PRINCESS, null, null, null, null, NPC_BUTCHER, null, null },
{  null, null, null, NPC_MOUNTAIN_KING, null, null, null, null, null, null, null },
{  null, null, NPC_CITIZEN_MALE, null, null, HERO_BABY, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_MAGIC_SHOP, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, NPC_BLACKSMITH, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_FIRST_2, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, NPC_CITIZEN_MALE, null, null, null, NPC_BLACKSMITH, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, HERO_BABY, null, null, NPC_ALCHEMIST, null, null },
{  null, null, NPC_PRINCESS, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_MOUNTAIN_KING, null, null, null, NPC_BUTCHER, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_MAGIC_SHOP, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_FIRST_3, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_CITIZEN_MALE, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, NPC_PRINCESS, NPC_MOUNTAIN_KING, null, null },
{  null, null, null, NPC_BLACKSMITH, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, HERO_BABY, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, NPC_BUTCHER, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, NPC_ALCHEMIST, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, NPC_MAGIC_SHOP, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_FIRST_4, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, NPC_MAGIC_SHOP, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, NPC_CITIZEN_MALE, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_MOUNTAIN_KING, null, null, null, null, null, null, null },
{  null, null, null, null, NPC_PRINCESS, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, NPC_BUTCHER, null, HERO_BABY, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, NPC_ALCHEMIST, null, null, null, null, null, null, null, null, null },
{  null, null, null, NPC_BLACKSMITH, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_1, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, ORC_SHAMAN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, ORC_SHAMAN, null, null },
{  null, null, null, ORC_SHAMAN, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, ORC_SHAMAN, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GNOLL_SCOUT, null, null, null, null, null, null, null, GNOLL_SCOUT, null },
{  null, null, null, null, null, GNOLL_OVERSEER, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_2, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, SWAMPY, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MUDDY, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_OVERSEER, null, null, null, null, null, null },
{  null, null, null, null, null, null, MUDDY, null, null, null, null },
{  null, MUDDY, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, SWAMPY, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, SWAMPY, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_3, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GOBLIN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MASKED_ORC, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GOBLIN, null, null, null, null, null, null, null, null },
{  null, MASKED_ORC, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, MUDDY, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, MASKED_ORC, null, null, null, null, null, null, null },
{  null, null, null, null, null, GOBLIN, null, null, null, MASKED_ORC, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_OVERSEER, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MUDDY, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_4, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GOBLIN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, GOBLIN, null, null, null, null, null, GOBLIN, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GNOLL_SCOUT, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_SCOUT, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GOBLIN, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GOBLIN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_5, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_SCOUT, null, null, null },
{  null, null, null, null, null, GOBLIN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, ORC_SHAMAN, null },
{  null, GOBLIN, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GNOLL_SCOUT, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, ORC_SHAMAN, null, null, null, null, null, null, null, null },
{  null, null, null, null, GOBLIN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, null, null, null, null, null, ORC_SHAMAN, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_SCOUT, null, null },
{  null, null, null, null, null, null, GOBLIN, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_6, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_SCOUT, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_SCOUT, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_BRUTE, null, null, null, null, null, null, null },
{  null, null, GOBLIN, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GOBLIN, null, null, GNOLL_SCOUT, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_BRUTE, null, null, null, null },
{  null, null, null, null, null, null, null, null, GOBLIN, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_SCOUT, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_7, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MASKED_ORC, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, GNOLL_BRUTE },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_BRUTE, null, null, null, null, GNOLL_BRUTE, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_BRUTE, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_BRUTE, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_8, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MASKED_ORC, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MASKED_ORC, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, MASKED_ORC, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MASKED_ORC, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_9, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, MASKED_ORC, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, MASKED_ORC, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MASKED_ORC, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MASKED_ORC, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_10, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MASKED_ORC, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, MASKED_ORC, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MASKED_ORC, null, null, null, null, null },
{  null, null, null, null, null, null, null, MASKED_ORC, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, MASKED_ORC, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_11, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MASKED_ORC, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, MASKED_ORC, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, MASKED_ORC, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, MASKED_ORC, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, MASKED_ORC, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, MASKED_ORC, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_12, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MASKED_ORC, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, MASKED_ORC, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, MASKED_ORC, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_13, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GOBLIN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GOBLIN, null, GNOLL_SCOUT, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GOBLIN, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, GNOLL_SCOUT, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GOBLIN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_SCOUT, null, null, null, null, null },
{  null, null, null, null, GOBLIN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_14, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, ORC_SHAMAN, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GNOLL_SCOUT, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, ORC_SHAMAN, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, ORC_SHAMAN, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, ORC_SHAMAN, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_SCOUT, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_15, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MASKED_ORC, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_BRUTE, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_BRUTE, null, null, null, null, null, MASKED_ORC, null },
{  null, MASKED_ORC, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MASKED_ORC, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_BRUTE, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MASKED_ORC, null, GNOLL_BRUTE, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_16, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MASKED_ORC, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_BRUTE, null, null, null, null },
{  null, null, null, null, null, null, null, null, MASKED_ORC, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_BRUTE, null, null, null, null },
{  null, null, null, null, MASKED_ORC, null, null, null, null, null, null },
{  null, null, GNOLL_BRUTE, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_BRUTE, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, MASKED_ORC, null, null, null, null, MASKED_ORC, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_17, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GNOLL_SCOUT, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, MASKED_ORC, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, MASKED_ORC, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, GNOLL_SCOUT, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, MASKED_ORC, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_SCOUT, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MASKED_ORC, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GNOLL_SCOUT, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MASKED_ORC, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_18, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, MUDDY, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_SCOUT, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, MUDDY, null, null },
{  null, null, GNOLL_SCOUT, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, GNOLL_SCOUT, null },
{  null, MUDDY, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, MUDDY, null, null },
{  null, null, null, null, null, null, null, null, null, GNOLL_SCOUT, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_SCOUT, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_19, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, MUDDY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, MUDDY, null, null, null, null },
{  null, null, null, null, null, null, null, null, GNOLL_BRUTE, null, null },
{  null, MUDDY, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, MUDDY, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, null, null, null, null, MUDDY, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_REGULAR_20, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_BRUTE, null, GOBLIN, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, GOBLIN, null, null, null, null },
{  null, null, null, null, null, null, null, GNOLL_BRUTE, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, GOBLIN, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, GNOLL_BRUTE, null, null, null, null, GOBLIN, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, GOBLIN, null, GNOLL_BRUTE, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, GNOLL_BRUTE, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_BOSS_1, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, WOGOL, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, SKELET, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, WOGOL, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, WOGOL, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, NECROMANCER, null, null, null },
{  null, null, null, null, BOSS_BIG_DEMON, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, NECROMANCER, null, null, null, WOGOL, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, WOGOL, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_BOSS_2, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, TINY_ZOMBIE, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, TINY_ZOMBIE, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, SKELET, null, null, null, null, null, null, null, null },
{  null, null, null, null, BOSS_BIG_DEMON, null, null, SKELET, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, ICE_ZOMBIE, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, SKELET, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, ICE_ZOMBIE, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_BOSS_3, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, ICE_ZOMBIE, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, WOGOL, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, ICE_ZOMBIE, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, BOSS_BIG_DEMON, null, null, WOGOL, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, NECROMANCER, null, null, null, null, null, null, null },
{  null, null, WOGOL, null, null, ICE_ZOMBIE, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
charactersInfoMap.put(RoomEnum.STAGE_3_BOSS_4, new CharacterEnum[][] { 
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, IMP, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  NECROMANCER, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, IMP, null, null },
{  null, null, null, null, null, null, null, null, null, null, null },
{  null, null, BOSS_BIG_DEMON, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, IMP, null, null, null, null, null },
{  null, null, null, NECROMANCER, null, null, null, null, null, null, null },
{  null, CHORT, null, null, null, null, null, null, null, null, null },
{  null, null, null, null, null, null, null, null, null, null, null }
});
//python-insert-char-end

    }

    public static HashMap<RoomEnum, CharacterEnum[][]> getCharactersInfo() {
        return charactersInfoMap;
    }
}
