package com.appatstudio.epicdungeontactics2.global.enums;

public enum CharacterEnum {
    HERO_ELF, HERO_KNIGHT, HERO_WIZZARD, HERO_LIZARD, HERO_PIRATE, HERO_NINJA, HERO_BABY,


    TINY_ZOMBIE, ZOMBIE, ICE_ZOMBIE, MUDDY,
    BIG_ZOMBIE,

    SWAMPY, ORC_SHAMAN, ORC_WARRIOR, GOBLIN, MASKED_ORC,
    BOSS_OGRE,

    SKELET, CHORT, IMP, NECROMANCER, WOGOL,
    BOSS_BIG_DEMON,

    CENTAUR_MALE, CENTAUR_FEMALE, ENT, TROLL, WOLF,
    MUSHROOM_SMALL, MUSHROOM_NORMAL, MUSHROOM_LARGE, BEAR,
    BOSS_FOREST_GUARDIAN,

    ELVEN_PRINCESS, ELVEN_KING, ELVEN_KNIGHT,
    GNOLL_BRUTE, GNOLL_OVERSEER,
    GNOLL_SCOUT, GNOLL_SHAMAN,


    NPC_ALCHEMIST, NPC_THIEF, NPC_CITIZEN_FEMALE, NPC_CITIZEN_MALE, NPC_BUTCHER, NPC_MOUNTAIN_KING,
    NPC_PRINCESS, NPC_BISHOP,
    NPC_NUN_FAT, NPC_NUN_NORMAL,
    NPC_MAGIC_SHOP, NPC_BLACKSMITH,
    NPC_KING, NPC_KNIGHT_ELITE,

    PET_KNIGHT, PET_DOG, PET_HUNTER


}
