package com.appatstudio.epicdungeontactics2.global.enums;

public enum CharacterEnum {
    HERO_ELF, HERO_KNIGHT, HERO_WIZZARD, HERO_LIZARD, HERO_PIRATE, HERO_NINJA, HERO_BABY,


    TINY_ZOMBIE, ZOMBIE, ICE_ZOMBIE, MUDDY,
    BIG_ZOMBIE,

    SWAMPY, ORC_SHAMAN, ORC_WARRIOR, GOBLIN, MASKED_ORC,
    OGRE,

    SKELET, CHORT, IMP, NECROMANCER, WOGOL,
    BIG_DEMON

}
