package com.appatstudio.epicdungeontactics2.global.enums;

public enum FontEnum {

    //menu
    MENU_HERO_TITLE_UNLOCKED, MENU_HERO_TITLE_LOCKED,
    MENU_HERO_DESCRIPTION_UNLOCKED, MENU_HERO_DESCRIPTION_LOCKED,
    MENU_HERO_DESCRIPTION_UNLOCKED_GREEN, MENU_HERO_DESCRIPTION_UNLOCKED_RED,
    MENU_PERK_TITLE, MENU_PERK_DESCRIPTION,

    STAT_HP, STAT_MP, STAT_EXP, STAT_DESC, SMALL_STAT_DESC,

    //game
    COMMUNICATE_RED, COMMUNICATE_DARK_RED,
    COMMUNICATE_WHITE, COMMUNICATE_GOLD,
    COMMUNICATE_GRAY,
    ENEMY_BAR_NAME, BOSS_BAR_NAME, PET_BAR_NAME,

    ITEM_TITLE_WHITE, ITEM_TITLE_GREEN, ITEM_TITLE_BLUE, ITEM_TITLE_VIOLET, ITEM_TITLE_ORANGE, ITEM_TITLE_RED,
    ITEM_DESC,

    LVL_POINTS_NUMBER,

    ITEM_DESC_YELLOW, EFFECT_DURATION_FONT
}
