package com.appatstudio.epicdungeontactics2.global.enums;

public enum FontEnum {

    //menu
    MENU_HERO_TITLE_UNLOCKED, MENU_HERO_TITLE_LOCKED,
    MENU_HERO_DESCRIPTION_UNLOCKED, MENU_HERO_DESCRIPTION_LOCKED,
    MENU_PERK_TITLE, MENU_PERK_DESCRIPTION,

    //game
    COMMUNICATE_RED, COMMUNICATE_DARK_RED,
    COMMUNICATE_WHITE, COMMUNICATE_GOLD,
    COMMUNICATE_GRAY,

    EFFECT_DURATION_FONT
}
