package com.appatstudio.epicdungeontactics2.global.enums;

public enum GuiCharacterAnimationEnum {
    GUI_HERO_ELF, GUI_HERO_KNIGHT, GUI_HERO_WIZZARD, GUI_HERO_LIZARD, GUI_HERO_NINJA, GUI_HERO_PIRATE, GUI_HERO_BABY,
    GUI_NPC_ALCHEMIST, GUI_NPC_THIEF, GUI_NPC_CITIZEN_FEMALE, GUI_NPC_CITIZEN_MALE, GUI_NPC_BUTCHER, GUI_NPC_MOUNTAIN_KING,
    GUI_NPC_PRINCESS, GUI_NPC_BISHOP,
    GUI_NPC_NUN_FAT, GUI_NPC_NUN_NORMAL,
    GUI_NPC_MAGIC_SHOP, GUI_NPC_BLACKSMITH,
    GUI_NPC_KING, GUI_NPC_KNIGHT_ELITE,
}
