package com.appatstudio.epicdungeontactics2.global.enums;

public enum  GuiElementEnum {
    BRONZE_MEDAL, SILVER_MEDAL, GOLD_MEDAL, DIAMOND_MEDAL,

    BOTTOM_BAR,
    BRONZE_BUTTON_WIDE, STONE_BUTTON_WIDE, SILVER_BUTTON_WIDE, YELLOW_BUTTON_WIDE,
    BRONZE_COMMUNICATE_WINDOW, STONE_COMMUNICATE_WINDOW, SILVER_COMMUNICATE_WINDOW, YELLOW_COMMUNICATE_WINDOW,

    SETTINGS_ICON
}
