package com.appatstudio.epicdungeontactics2.global.enums;

public enum  GuiElementEnum {
    BRONZE_MEDAL, SILVER_MEDAL, GOLD_MEDAL, DIAMOND_MEDAL,

    BOTTOM_BAR,
    BRONZE_BUTTON_WIDE, STONE_BUTTON_WIDE, SILVER_BUTTON_WIDE, YELLOW_BUTTON_WIDE,
    BRONZE_COMMUNICATE_WINDOW, STONE_COMMUNICATE_WINDOW, SILVER_COMMUNICATE_WINDOW, YELLOW_COMMUNICATE_WINDOW,

    IDLE_INCOME_BANNER,

    LVL_EXP_BAR, LVL_EXP_BAR_BG,

    BLACK,

    BLACK_ALPHA_50percent,

    ARROW_LEFT, ARROW_RIGHT,

    SETTINGS_ICON,
    COINS,
    POINTS_PER_LVL_ICON,

    CAMP_UPGRADE_BUTTON, FINANCES_UPGRADE_BUTTON,

    FINANCES_BG,

    BACK_ICON, STATS_ICON,

    PLAYER_STAT_PROGRESS_BG, PLAYER_STAT_PROGRESS_BAR,

    HEAD_ELF, HEAD_KNIGHT, HEAD_WIZARD, HEAD_LIZARD, HEAD_NINJA, HEAD_PIRATE, HEAD_BABY,

    HEAD_BUTCHER, HEAD_ALCHEMIST, HEAD_LUGGAGE_CARRIAGE, HEAD_BLACKSMITH, HEAD_PRINCESS, HEAD_MAGIC_SHOP, HEAD_MOUNTAIN_KING,
    HEAD_BUTCHER_ZERO, HEAD_ALCHEMIST_ZERO, HEAD_LUGGAGE_CARRIAGE_ZERO, HEAD_BLACKSMITH_ZERO, HEAD_PRINCESS_ZERO, HEAD_MAGIC_SHOP_ZERO, HEAD_MOUNTAIN_KING_ZERO,

    DAY_LIGHT_TEXTURE, NIGHT_LIGHT_TEXTURE,

    STATUS_BARS_BG, STATUS_BARS_BORDER,
    HP_BAR, EXP_BAR,

    EQUIPMENT_ICON, QUEST_ICON, MAP_ICON,

    RUN_QUIT_WINDOW,

    MENU_BG1, MENU_BG2,

    //equipment window
    BACKPACK_GRID_1x2, BACKPACK_GRID_2x4, BACKPACK_GRID_3x6,
    //ITEM_BG_EMPTY, ITEM_BG_EQUIPPED, ITEM_BG_GREEN, ITEM_BG_BLUE, ITEM_BG_YELLOW,
    SEGMENT_HERO, SEGMENT_BACKPACK, SEGMENT_ITEM,
    //ITEM_DROP_BUTTON, ITEM_EQUIP_BUTTON,

    //map window
    //MAP_BG, MAP_ROOM_CLEAR, MAP_ROOM_UNKNOWN, MAP_ROOM_BOSS, MAP_ROOM_ITEM, MAP_ROOM_WAY_DOWN
}
