package com.appatstudio.epicdungeontactics2.global.enums;

public enum GuiStringEnum {
    SELECT, AVAILABLE_AT_STAGE, COST, UNLOCK, JUST_UPGRADE, HIRE, FIGHT, REROLL, SELECT_PERK, BACK, STATS, PLAYER_STATS,
    UPGRADE, INVEST, YOUR_INVESTMENTS,
    CURR_INCOME, DAY, IDLE_INCOME_COLLECTED,

    YES, NO, QUIT_RUN_QUESTION,

    MAXED_OUT, STAGE,

    FINISH, NO_HERO_LEFT,

    NOT_POSSIBLE_IN_FIGHT,
    DROP,

    MELE_DMG,
    DISTANCE_DMG,
    RANGE,
    ARMOR,
    MOVE_SPEED_COST, VALUE, DMG_EFFECT, RANGE_EFFECT, CHANCE_FOR, CRIT_CHANCE, HP_EFFECT, MP_EFFECT, EXP_EFFECT,
    SPEED, MISS_CHANCE, PICK,

    ITEMS_TO_PICK, NO_SPACE,

    CHANGE_ROOM, GO_DOWN , BUY , SELL ,

    CHOOSE_NEXT_HERO, KEEP_ITEMS, GO, KEEP, WASTE, JUST_FINISH_GAME
}
