package com.appatstudio.epicdungeontactics2.global.enums;

public enum GuiStringEnum {
    SELECT, AVAILABLE_AT_STAGE, COST, UNLOCK, JUST_UPGRADE, HIRE, FIGHT, REROLL, SELECT_PERK, BACK, STATS, PLAYER_STATS,
    UPGRADE, INVEST, YOUR_INVESTMENTS,
    CURR_INCOME, DAY, IDLE_INCOME_COLLECTED,

    YES, NO, QUIT_RUN_QUESTION,

    MAXED_OUT, STAGE
}
