package com.appatstudio.epicdungeontactics2.global.enums;

public enum MapElementAnimationEnum {
    LAVA, WATER, CHEST, TORCH, CANDLE, CANDLE_BIG,
    TREE_1, TREE_7, TREE_12, TREE_4, TREE_6, TREE_11,
    TREE_3, TREE_10, TREE_2, TREE_9, TREE_8, TREE_5, GLOWING_STONE_1, LAVA_ROCK_SMOKE_4,
    LAVA_ROCK_SMOKE_2, GLOWING_STONE_3, LAVA_ROCK_SMOKE_3,
    GLOWING_STONE_2, LAVA_ROCK_SMOKE_1, GLOWING_STONE_4,

}
