package com.appatstudio.epicdungeontactics2.global.enums.soundEnum;

public enum SoundEnum {
    ARMOR_DRESSING, BOOK_READ, BOSS_DEFEATED, BOW_HIT, BOW_SHOT,
    COINS_PICKUP, COINS_SPENT, EATING, FIST_HIT, FIST_PUNCH, INTERFACE_TAP,
    LVL_UP, MELE_WEAPON_WEAR, POTION_DRINKING, SHOCK_SPELL, SPELL_EXPLOSION,
    STAGE_1_STEP, SWORD_HIT, STAGE_2_STEP, STAGE_3_STEP, HERO_DOWN, HEROES_ALL_DOWN
}
